name: knowgo_vehicle_simulator
description: >-
  An interactive multi-platform Connected Car simulator for generating and streaming realistic
  vehicle telemetry.
publish_to: 'none'
repository: https://github.com/knowgoio/knowgo-vehicle-simulator
issue_tracker: https://github.com/knowgoio/knowgo-vehicle-simulator/issues
documentation: https://knowgoio.github.io/knowgo-vehicle-simulator/docs
version: 1.2.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.1
  vin_decoder: ^0.2.1-nullsafety
  random_string: ^2.1.0
  vector_math: ^2.0.8
  uuid: ^3.0.6
  get_it: ^7.2.0
  js: ^0.6.3
  font_awesome_flutter: ^10.0.0
  yaml: ^3.1.0
  auto_size_text: ^3.0.0
  mqtt_client: ^9.6.5
  shelf_router: ^1.1.2
  http: ^0.13.3
  path_provider: ^2.0.2
  kafka:
    git:
      url: https://github.com/adaptant-labs/kafka
      ref: kafka-0.10-nullsafety
  knowgo:
    git:
      url: https://github.com/knowgoio/knowgo-client-dart
  csv: ^5.0.0
  flutter_picker: ^2.0.0
  prometheus_client_shelf: ^1.0.0
  jaguar_jwt: ^3.0.0
  path_to_regexp: ^0.4.0
  args: ^2.3.0
  shelf_web_socket: ^1.0.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.4.0
  flutter_native_splash: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
      - asset: fonts/proximanovalight.ttf
      - asset: fonts/proxima-nova-alt-bold.ttf
        weight: 700

    - family: Icomoon
      fonts:
      - asset: fonts/icomoon.ttf

msix_config:
  display_name: KnowGo Vehicle Simulator
  publisher_display_name: Adaptant Solutions AG
  identity_name: AdaptantSolutionsAG.KnowGoVehicleSimulator
  publisher: CN=F98FFF93-A117-4459-8FFE-1761BACA0060
  msix_version: 1.2.0.0
  logo_path: web/icons/icon-512.png
  start_menu_icon_path: web/icons/icon-512.png
  tile_icon_path: web/icons/icon-512.png
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,internetClientServer,privateNetworkClientServer'

flutter_native_splash:
  color: "#ffffff"
  image: snap/gui/knowgo-vehicle-simulator.png
  fullscreen: true
