name: knowgo_simulator_desktop
description: KnowGo Vehicle Simulator
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  vin_decoder: ^0.1.2
  random_string:
  vector_math: ^2.0.8
  uuid: ^2.1.0
  args: ^1.6.0
  get_it: ^4.0.2
  font_awesome_flutter: ^8.8.1
  yaml: ^2.2.1
  auto_size_text: ^2.1.0
  knowgo:
    git:
      url: https://github.com/knowgoio/knowgo-client-dart

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
      - asset: fonts/proximanovalight.ttf
      - asset: fonts/proxima-nova-alt-bold.ttf
        weight: 700

    - family: Icomoon
      fonts:
      - asset: fonts/icomoon.ttf
