name: knowgo_simulator_desktop
description: KnowGo Vehicle Simulator
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^5.0.0
  vin_decoder: ^0.1.3
  random_string:
  vector_math: ^2.0.8
  uuid: ^2.1.0
  args: ^2.0.0
  get_it: ^6.0.0
  font_awesome_flutter: ^8.8.1
  yaml: ^3.1.0
  auto_size_text: ^2.1.0
  mqtt_client: ^8.1.0
  kafka:
    git:
      url: https://github.com/dart-kafka/kafka
      ref: kafka-0.10
  knowgo:
    git:
      url: https://github.com/knowgoio/knowgo-client-dart

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
      - asset: fonts/proximanovalight.ttf
      - asset: fonts/proxima-nova-alt-bold.ttf
        weight: 700

    - family: Icomoon
      fonts:
      - asset: fonts/icomoon.ttf
