apiVersion: v1
kind: Service
metadata:
  name: knowgo-vehicle-simulator
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: knowgo-vehicle-simulator
  ports:
    - protocol: TCP
      port: 8086
