name: Deploy Flutter Web Demo and Docs

on:
  workflow_run:
    workflows: ["Generate MkDocs Documentation"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-web
        shell: bash
      - run: flutter pub get
        shell: bash
      - run: flutter build web --release --no-sound-null-safety
        shell: bash
      - run: mkdir -p build/web/lib/simulator
        shell: bash
      - run: dart compile js --no-sound-null-safety lib/simulator/vehicle_event_worker.dart -o build/web/lib/simulator/vehicle_event_worker.js
        shell: bash
      - run: git config user.name github-actions
        shell: bash
      - run: git config user.email github-actions@github.com
        shell: bash
      - uses: actions/checkout@v2
        with:
          repository: knowgoio/knowgo-vehicle-simulator
          path: build/web/docs
          ref: gh-pages-docs
      - run: touch build/web/.nojekyll
        shell: bash
      - run: git --work-tree build/web add --all
        shell: bash
      - run: git commit -m "Automatic deployment by github-actions"
        shell: bash
      - run: git push origin HEAD:gh-pages --force
        shell: bash
