name: Deploy Flutter Web Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: pmundt/flutter-gh-pages@v4
        with:
          deployTo: gh-pages-demo
          additionalBuildFlags: --no-sound-null-safety
          additionalDart2JsFlags: --no-sound-null-safety
          webWorkerSource: lib/simulator/vehicle_event_worker.dart
          webWorkerDestination: lib/simulator/vehicle_event_worker.js
